### ISSUE TITLE
Data-ID Value

### ISSUE THREAD

**Issue by emresaracoglu** [vladthecodeimpaler/floatingMenu#1]
Hello,
A very nice menu but I do not use/
I added **data-info='123'** in link

```
<div class='designer-actions'> 
<a class='icon ion-ios-more' data-info='123' 
href='javascript:void(null);' 
data-action='show-actions-menu' 
data-fm-floatTo='right'>{$row[0]}</a>
</div>
```

```
        var myDiv = document.querySelector('.designer-actions');
        $.floatingMenu({ 
            selector: '.designer-actions a[data-action="show-actions-menu"]',
            items: [
                {
                    icon : 'ion-social-youtube',
                    title : 'Youtube',
                    action : 'https://youtube.com/'+ myDiv.dataset.info,
                    blank : true, // opens link in new tab (optional)
                    close : false, // close the menu after the action happene (optional)
                }
            ]
        });
```

OUT: youtube.com/undefineed 

Why am I getting this error?

**Comment by vladthecodeimpaler** [comment]
Hi emresaracoglu

Im gonna take a look today.

**Comment by vladthecodeimpaler** [comment]
I am at work at the moment and i cant think of a solution right now but the problem is as follows

`var myDiv = document.querySelector('.designer-actions');`

your selector for **myDiv** does not contain the floating menu, just your element on which you call the floating menu to show upon .

**Comment by emresaracoglu** [comment]
Thank you for interest.
I asked ths issue on [StackOverflow ](http://stackoverflow.com/questions/39294149/getting-data-id-undefined)
if you find a solution, I'd be happy

**Comment by deviantmk** [comment]
Hello

i will respond here and on stackoverflow as well

https://jsfiddle.net/2bwnd9pq/

notice the problem, you are using the selector id='designer-actions', so you are accessing the data on that element only. Another problem is data-idNo is not a valid value when you access it with dataset.idNo, it should be dataset.idno (all lowercase).

I think what you are trying to do is feed youtube links dynamically, so you should just generate that array beforehand and just pass it to the menu `items: [your array of objects here]`

describe your situation/use cause and i might be able to help you a bit more

Regards, Vlad

**Comment by vladthecodeimpaler** [comment]
Hello

https://jsfiddle.net/2bwnd9pq/

notice the problem, you are using the selector id='designer-actions', so you are accessing the data on that element only. Another problem is data-idNo is not a valid value when you access it with dataset.idNo, it should be dataset.idno (all lowercase).

I think what you are trying to do is feed youtube links dynamically, so you should just generate that array beforehand and just pass it to the menu `items: [your array of objects here]`

describe your situation/use cause and i might be able to help you a bit more

Regards, Vlad

**Comment by emresaracoglu** [comment]
I'm trying to create a menu of table. **Thank you** for your solution.
Can you help me again for variable data?

`data-tableName='ExampleTable1'`

 Is it possible to be variable?
https://jsfiddle.net/emresaracoglu/80we8pbr/8/

**Comment by emresaracoglu** [comment]
Hi, I need you valuable help.

**Comment by vladthecodeimpaler** [comment]
hi emresaracoglu 

can you explain in a bit more detailed way what exactly you want to achieve.
I am sorry but i cant understand what you really need.

Regards, Vlad

**Comment by emresaracoglu** [comment]
Hello,
I prepare video for you. I would hope that would be useful
[Video on YouTube](https://www.youtube.com/watch?v=7Ca1iui2lFM)

**Comment by vladthecodeimpaler** [comment]
alright i get it, i will fix something up after working hours

**Comment by emresaracoglu** [comment]
Hi, I'm looking forward :+1:

**Comment by vladthecodeimpaler** [comment]
https://jsfiddle.net/80we8pbr/10/

something like this should do the job

**Comment by emresaracoglu** [comment]
Thank you but I get "undefined"

`https://example.com/?id=undefined&table=undefined`

https://jsfiddle.net/emresaracoglu/80we8pbr/11/

**Comment by vladthecodeimpaler** [comment]
try the first two

**Comment by emresaracoglu** [comment]
Vlad, you know? 
you are amazing person!

@vladthecodeimpaler

**Comment by vladthecodeimpaler** [comment]
@emresaracoglu im glad i could help :smile:
